USER-SUPPLIED VALUES:
controller:
  admissionWebhooks:
    enabled: false
  autoscaling:
    enabled: true
    maxReplicas: 5
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  config:
    http-snippet: |
      more_set_headers "Server: ";
      server {
        listen 18080;

        location /nginx_status {
          allow all;
          stub_status on;
        }

        location / {
          return 404;
        }
      }
    nginx-status-ipv4-whitelist: 10.131.188.64/26
    proxy-set-headers: eot-iot-tld-int/int-tld-api-custom-headers
    proxy-hide-headers: server, X-Powered-By, X-AspNet-Version, X-AspNet-Mvc-Version
    server-tokens: "False"
  image:
    digest: ""
    repository: dtr.it.sncf.fr/gpf.04255/k8s.nginx-ingress-controller
    tag: 0.34.1
  ingressClass: nginx-api
  lifecycle:
    preStop:
      exec:
        command:
        - sh
        - -c
        - sleep 30
  minAvailable: 1
  podAnnotations:
    ad.datadoghq.com/nginx-ingress-eot-iot-tld-int.check_names: '["nginx", "nginx_ingress_controller"]'
    ad.datadoghq.com/nginx-ingress-eot-iot-tld-int.init_configs: '[{},{}]'
    ad.datadoghq.com/nginx-ingress-eot-iot-tld-int.instances: '[{"nginx_status_url":"http://%%host%%:18080/nginx_status"},{"prometheus_url":
      "http://%%host%%:10254/metrics"}]'
    ad.datadoghq.com/nginx-ingress-eot-iot-tld-int.logs: '[{"service": "controller",
      "source":"nginx_ingress_controller"}]'
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.131.188.64/26
  podLabels:
    customized: "true"
  priorityClassName: ttdok
  replicaCount: 2
  resources:
    limits:
      cpu: 700m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  scope:
    enabled: true
    namespace: eot-iot-tld-int
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    externalTrafficPolicy: Local
    labels: {}
    loadBalancerIP: 10.131.188.107
defaultBackend:
  enabled: true
  priorityClassName: ttdok
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
fullnameOverride: eot-iot-tld-api-int-nginx-ingress
rbac:
  scope: true
